package com.zvonok.service.enums;

public enum RoomEventsType {
	ROOM_CREATED,
	ROOM_UPDATE,
	ROOM_DELETED,
	ROOM_MESSAGES_CLEARED,
	ROOM_MEMBERS_ADDED,
	ROOM_MEMBER_JOINED_BY_INVITE,
	ROOM_MEMBER_LEFT,
	BOOMBOX_STARTED,
	BOOMBOX_ENDED,
	TRACK_ADDED,
	TRACK_REMOVED,
	TRACK_CHANGED,
	PLAYBACK_PLAY,
	PLAYBACK_PAUSE,
	PLAYBACK_SEEK,
	QUEUE_UPDATED,
	VOTE_UPDATED,
	SYNC_STATE
}
